**Bag of words**

A bag-of-words is a representation of text that describes the occurrence of words within a document. It involves two things:

A vocabulary of known words.
A measure of the presence of known words.

**Bag-of-words example**

Let's assume we have three sentences in our vocabulary.

Sentence 1: Data science is fun and interesting

Sentence 2: Data science is fun

Sentence 3: science is interesting

The unique words in the sentences are : [data, science, is, fun, and, interesting]. Hence, the bag of words vectors for the above sentences will be

Sentence 1: [1, 1, 1, 1, 1, 1]

Sentence 2: [1, 1, 1, 1, 0, 0]

Sentence 3: [0, 1, 1, 0, 0, 1]

**Bag of Words Algorithm Implementation**

In [ ]:

''' vectorize() function takes list of words in a sentence as input
    and returns a vector of size of filtered_vocab.It puts 0 if the
    word is not present in tokens and count of token if present.'''

def vectorize(tokens):
    vector=[]
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector

In [ ]:
'''unique() functions returns a list in which the order remains
    same and no item repeats.Using the set() function does not
    preserve the original ordering,so i didnt use that instead'''

def unique(sequence):
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]
#create a list of stopwords.You can import stopwords from nltk too
stopwords=["to","was","a"]
#list of special characters.You can use regular expressions too
special_char=[",",":"," ",";",".","?"]

In [ ]:


string1 = "Data science is fun and interesting"
string2 = "Data science is fun"
string3 = "science is interesting"

#converting strings to lower case
string1=string1.lower()
string2=string2.lower()
string3=string3.lower()

#split the sentences into tokens
tokens1=string1.split()
tokens2=string2.split()
tokens3=string3.split()

print(tokens1)
print(tokens2)
print(tokens3)

['data', 'science', 'is', 'fun', 'and', 'interesting']
['data', 'science', 'is', 'fun']
['science', 'is', 'interesting']

In [ ]:
#create a vocabulary list
vocab=unique(tokens1+tokens2+tokens3)
print(vocab)


#filter the vocabulary list
filtered_vocab=[]

for w in vocab:
    if w not in stopwords and w not in special_char:
        filtered_vocab.append(w)
print("Final filtered vocabulary: ", filtered_vocab)



#convert sentences into vectords
vector1=vectorize(tokens1)
print("Sentence 1 vector :",vector1)

vector2=vectorize(tokens2)
print("Sentence 2 vector :",vector2)

vector3=vectorize(tokens3)
print("Sentence 3 vector :",vector3)

['data', 'science', 'is', 'fun', 'and', 'interesting']
Final filtered vocabulary:  ['data', 'science', 'is', 'fun', 'and', 'interesting']
Sentence 1 vector : [1, 1, 1, 1, 1, 1]
Sentence 2 vector : [1, 1, 1, 1, 0, 0]
Sentence 3 vector : [0, 1, 1, 0, 0, 1]

**Creating Bag of Words using sklearn library**

In [ ]:

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

string1 = "Data science is fun and interesting"
string2 = "Data science is fun"
string3 = "science is interesting"
string4 = "data is interesting"

doc = string1+string2+string3+string4

CountVec = CountVectorizer(ngram_range=(1,1))
#transform
Count_data = CountVec.fit_transform([string1,string2,string3,string4])

#create dataframe
# Use get_feature_names_out() instead of get_feature_names()
cv_dataframe=pd.DataFrame(Count_data.toarray(),columns=CountVec.get_feature_names_out())
print(cv_dataframe)

   and  data  fun  interesting  is  science
0    1     1    1            1   1        1
1    0     1    1            0   1        1
2    0     0    0            1   1        1
3    0     1    0            1   1        0

Note that the CountVectorize sorts the vocabulary alphabetically before generating vectors.

**Count Occurrence**

In [ ]:

count_vec = CountVectorizer()
count_occurs = count_vec.fit_transform([doc])
count_occur_df = pd.DataFrame((count, word) for word, count in zip(count_occurs.toarray().tolist()[0], count_vec.get_feature_names_out()))
count_occur_df.columns = ['Word', 'Count']
count_occur_df.sort_values('Count', ascending=False, inplace=True)
count_occur_df.head()

              Word  Count
6               is      4
5  interestingdata      2
7          science      2
0              and      1
1             data      1

**Normalized Count Occurrence**

In [ ]:

from sklearn.feature_extraction.text import TfidfVectorizer
norm_count_vec = TfidfVectorizer(use_idf=False, norm='l2')
norm_count_occurs = norm_count_vec.fit_transform([doc])
norm_count_occur_df = pd.DataFrame((count, word) for word, count in zip(
    norm_count_occurs.toarray().tolist()[0], norm_count_vec.get_feature_names_out()))
norm_count_occur_df.columns = ['Word', 'Count']
norm_count_occur_df.sort_values('Count', ascending=False, inplace=True)
norm_count_occur_df.head()

              Word     Count
6               is  0.742781
5  interestingdata  0.371391
7          science  0.371391
0              and  0.185695
1             data  0.185695